In [1]:
data = [
    "When life gives you lemons, make lemonade! 🙂",
    "She bought 2 lemons for $1 at Maven Market.",
    "A dozen lemons will make a gallon of lemonade. [AllRecipes]",
    "lemon, lemon, lemons, lemon, lemon, lemons",
    "He's running to the market to get a lemon — there's a great sale today.",
    "Does Maven Market carry Eureka lemons or Meyer lemons?",
    "An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",
    "iced tea is my favorite"
]

In [2]:
import pandas as pd
pd.set_option('display.max_colwidth',None)

In [3]:
df=pd.DataFrame(data=data,columns=['sentence'])

In [4]:
df

                                                                  sentence
0                             When life gives you lemons, make lemonade! 🙂
1                              She bought 2 lemons for $1 at Maven Market.
2              A dozen lemons will make a gallon of lemonade. [AllRecipes]
3                               lemon, lemon, lemons, lemon, lemon, lemons
4  He's running to the market to get a lemon — there's a great sale today.
5                   Does Maven Market carry Eureka lemons or Meyer lemons?
6            An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]
7                                                  iced tea is my favorite

In [5]:
df["sentence_cleaned"]=df["sentence"].str.lower()

In [6]:
df

,sentence,sentence_cleaned
0,"When life gives you lemons, make lemonade! 🙂","when life gives you lemons, make lemonade! 🙂"
1,She bought 2 lemons for $1 at Maven Market.,she bought 2 lemons for $1 at maven market.
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],a dozen lemons will make a gallon of lemonade. [allrecipes]
3,"lemon, lemon, lemons, lemon, lemon, lemons","lemon, lemon, lemons, lemon, lemon, lemons"
4,He's running to the market to get a lemon — there's a great sale today.,he's running to the market to get a lemon — there's a great sale today.
5,Does Maven Market carry Eureka lemons or Meyer lemons?,does maven market carry eureka lemons or meyer lemons?
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]","an arnold palmer is half lemonade, half iced tea. [wikipedia]"
7,iced tea is my favorite,iced tea is my favorite

In [7]:
df["sentence_cleaned"] = df["sentence_cleaned"].str.replace(r"\[.*?\]", "", regex=True)

In [8]:
df

,sentence,sentence_cleaned
0,"When life gives you lemons, make lemonade! 🙂","when life gives you lemons, make lemonade! 🙂"
1,She bought 2 lemons for $1 at Maven Market.,she bought 2 lemons for $1 at maven market.
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],a dozen lemons will make a gallon of lemonade.
3,"lemon, lemon, lemons, lemon, lemon, lemons","lemon, lemon, lemons, lemon, lemon, lemons"
4,He's running to the market to get a lemon — there's a great sale today.,he's running to the market to get a lemon — there's a great sale today.
5,Does Maven Market carry Eureka lemons or Meyer lemons?,does maven market carry eureka lemons or meyer lemons?
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]","an arnold palmer is half lemonade, half iced tea."
7,iced tea is my favorite,iced tea is my favorite

In [9]:
df["sentence_cleaned"] = df["sentence_cleaned"].str.replace(r"[^a-z0-9\s]", "", regex=True)

In [10]:
df

,sentence,sentence_cleaned
0,"When life gives you lemons, make lemonade! 🙂",when life gives you lemons make lemonade
1,She bought 2 lemons for $1 at Maven Market.,she bought 2 lemons for 1 at maven market
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],a dozen lemons will make a gallon of lemonade
3,"lemon, lemon, lemons, lemon, lemon, lemons",lemon lemon lemons lemon lemon lemons
4,He's running to the market to get a lemon — there's a great sale today.,hes running to the market to get a lemon theres a great sale today
5,Does Maven Market carry Eureka lemons or Meyer lemons?,does maven market carry eureka lemons or meyer lemons
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",an arnold palmer is half lemonade half iced tea
7,iced tea is my favorite,iced tea is my favorite

In [11]:
def lower_replace(series):
    series = series.str.lower()
    series = series.str.replace(r"\[.*?\]", "", regex=True)
    series = series.str.replace(r"[^a-z0-9\s]", "", regex=True)
    return series

In [12]:
df['sentence_f_cleaned'] = lower_replace(df['sentence'])

In [13]:
import spacy as sp
nlp = sp.load('en_core_web_sm')

In [14]:
text = 'when life gives you lemons make lemonade'
doc = nlp(text)

In [15]:
def important_words(sentence):
    doc = nlp(sentence)
    words = []

    for token in doc:
        if not token.is_stop:
            words.append(token.lemma_)

    sentence = ' '.join(words)
    return sentence

In [16]:
sentence = 'i was playing cricket there were many friends'
imp_words = important_words(sentence)
imp_words

'play cricket friend'

In [17]:
df['final_sentence'] = df['sentence_f_cleaned'].apply(important_words)

In [18]:
df

,sentence,sentence_cleaned,sentence_f_cleaned,final_sentence
0,"When life gives you lemons, make lemonade! 🙂",when life gives you lemons make lemonade,when life gives you lemons make lemonade,life give lemon lemonade
1,She bought 2 lemons for $1 at Maven Market.,she bought 2 lemons for 1 at maven market,she bought 2 lemons for 1 at maven market,buy 2 lemon 1 maven market
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],a dozen lemons will make a gallon of lemonade,a dozen lemons will make a gallon of lemonade,dozen lemon gallon lemonade
3,"lemon, lemon, lemons, lemon, lemon, lemons",lemon lemon lemons lemon lemon lemons,lemon lemon lemons lemon lemon lemons,lemon lemon lemon lemon lemon lemon
4,He's running to the market to get a lemon — there's a great sale today.,hes running to the market to get a lemon theres a great sale today,hes running to the market to get a lemon theres a great sale today,s run market lemon s great sale today
5,Does Maven Market carry Eureka lemons or Meyer lemons?,does maven market carry eureka lemons or meyer lemons,does maven market carry eureka lemons or meyer lemons,maven market carry eureka lemon meyer lemon
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",an arnold palmer is half lemonade half iced tea,an arnold palmer is half lemonade half iced tea,arnold palmer half lemonade half ice tea
7,iced tea is my favorite,iced tea is my favorite,iced tea is my favorite,ice tea favorite

In [19]:
df = pd.DataFrame(data = data, columns = ['sentence'])

In [20]:
def nlp_pipeline(series):
    series = lower_replace(series)
    series = series.apply(important_words)
    return series

In [21]:
df['sentence_cleaned'] = nlp_pipeline(df['sentence'])

In [22]:
df

,sentence,sentence_cleaned
0,"When life gives you lemons, make lemonade! 🙂",life give lemon lemonade
1,She bought 2 lemons for $1 at Maven Market.,buy 2 lemon 1 maven market
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],dozen lemon gallon lemonade
3,"lemon, lemon, lemons, lemon, lemon, lemons",lemon lemon lemon lemon lemon lemon
4,He's running to the market to get a lemon — there's a great sale today.,s run market lemon s great sale today
5,Does Maven Market carry Eureka lemons or Meyer lemons?,maven market carry eureka lemon meyer lemon
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",arnold palmer half lemonade half ice tea
7,iced tea is my favorite,ice tea favorite